// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vevlvmjslewuhtiinioz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldmx2bWpzbGV3dWh0aWluaW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTc2NzAsImV4cCI6MjA3MTI3MzY3MH0.nfXNie2fdrzYWQ8f1HkzLnjiF2WQTlxkq6jCcF0qYsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});